# -*- coding: utf-8 -*-
"""17301133 Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OirM7a5aGh8Ls-KF-WOSrEyHJ8orLhDs

(P6.2.1)
"""

import datetime
import numpy as np
fname = "/content/drive/My Drive/Colab Notebooks/ex6-2-b-mountain-data.txt"
a = np.loadtxt(fname, dtype= ([("name", "S100"),("Height", "int"), ("First ascent", "S100"), ("First winter", "S100"), ("lat", "S100"), ("lon", "S100")]), skiprows=4, usecols=(0,1,2,3,4,5))

lowest = a[0][1]
for i in range(0,14):
  if(a[i][1] < lowest):
    lowest = a[i][1]
print("Lowest peak is:", lowest)

"""(P6.2.2)"""

import numpy as np
fname = "/content/drive/My Drive/Colab Notebooks/busiest_airports.txt"
data = np.genfromtxt(fname, dtype=[("code", "S10"), ("name", "S100"), ("location", "S100"),("lat", "f8"), ("lon", "f8")])

for i in range(0,6):
  print("Airport Code:",str(data[i][0]),"Latitude:",data[i][3],"Longitude:",data[i][4])

"""(P6.3.3)"""

import numpy as np
import pylab
data = np.genfromtxt("/content/drive/My Drive/Colab Notebooks/ex6-3-f-male-heights.txt", delimiter=" ", usecols=(1,2,3,4))
data = data[~np.any(np.isnan(data), axis=1)]
corr = np.corrcoef(data, rowvar=0)[0,1]
print('p-T correlation coefficient: {:.4f}'.format(corr))
pylab.scatter(*data.T, marker='.')
pylab.xlabel('$T$ /$\mathrm{^\circ C}$')
pylab.ylabel('$p$ /mbar')
pylab.show()

"""(P6.4.2)"""

import numpy as np
import statistics 
fname = "/content/drive/My Drive/Colab Notebooks/ex6-4-a-anscombe.txt"
a = np.genfromtxt(fname, dtype=[("x1", "f8"), ("y1", "f8"), ("x2", "f8"), ("y2", "f8"), ("x3", "f8"), ("y3", "f8"), ("x4", "f8"), ("y4", "f8")])

for i in range(0,11):
  arr = (a[i][0],a[i][1],a[i][2],a[i][3],a[i][4],a[i][5],a[i][0],a[i][6],a[i][7])
  mean = statistics.mean(arr)
  print("Mean of "+str(i+1)+"th Sample set is:",mean) 
  print("Variance of "+str(i+1)+"th Sample set is:",(statistics.variance(arr, xbar = mean)))
  print ()

