# -*- coding: utf-8 -*-
"""17301133Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WqNdj7gWFzK29UQdfzIvLaWlOlX36VMY

Prob 1
"""

import pandas as pd 
data = [['Anastasia', 12.5, 1, "yes"], ['Dima', 9,3,"no"], ['Katherine', 16.5, 2, "yes"],
        ["James",2.3,3,"no"],["Emily", 9, 2,"no"],["Michael", 20, 3,"yes"], ["Matthew", 14.5, 1,"yes"], ["Laura", 4.5, 1,"no"], ["Kevin", 8, 2,"no"],
        ["Jonas", 19, 1,"yes"]] 

df = pd.DataFrame(data, columns = ['Name', 'Scores', 'Attempts', 'Qualified']) 

print("Attempts of students:")
print(df["Attempts"])

for i in range(0,10):
  if df["Qualified"][i]=="yes":
    df["Qualified"][i]="1"
  else:
    df["Qualified"][i]="0"

df["Qualified"]

"""Prob 2"""

import pandas as pd
import matplotlib.pyplot as plt   

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/StockPriceData.csv', usecols=["Adj Close"]) 
df

x_data= range(0, df.shape[0]) 
print(x_data)
fig, ax = plt.subplots()
ax.plot(x_data, df['Adj Close'], marker='o', color='r')

df.rolling(100).mean().plot()

MySmoothe= df.rolling(100).mean()
df["Smooth"] = MySmoothe

df.head(20)

df=df.dropna()
df.rolling(100).mean().plot()